version: '3'

services:
  db:
    image: ${MYSQL_IMAGE}
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
     - ./Database:/docker-entrypoint-initdb.d
     #- ./db_container/data:/var/lib/mysql
    ports:
     - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"

  webapp:
    depends_on:
     - db
    build: .
    env_file: ./.env
    command: sh -c './wait-for db:${MYSQL_DOCKER_PORT} -- dotnet Nisshi.dll'
    environment:
     - ASPNETCORE_Nisshi_DatabaseProvider=${ASPNETCORE_Nisshi_DatabaseProvider}
     - ASPNETCORE_Nisshi_ConnectionString=${ASPNETCORE_Nisshi_ConnectionString}
     - ASPNETCORE_URLS=https://+;http://+
     - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Nisshi_CertificatePassword}
     - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Nisshi_CertificatePath}
     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_Nisshi_Environment}
    ports:
     - ${NISSHI_LOCAL_HTTP_PORT}:${NISSHI_DOCKER_HTTP_PORT}
     - ${NISSHI_LOCAL_HTTPS_PORT}:${NISSHI_DOCKER_HTTPS_PORT}
    volumes:
     - ~/.aspnet/https:/https:ro
